Upload access PDF to AWS
RockefellerArchiveCenter/dart_digitization pull request #11
Opened 2021-11-22 15:52 UTC by bonniegee

Fixes #10 

- add helper function to find access pdf
- add aws upload class with pdf upload method
- add test for aws upload
- add pdf upload to digitization pipeline

2021-11-22 22:41 UTC, helrond commented on tests/test_aws_upload.py
> +    assert s3_upload
Based on the way moto works, it seems like it should be possible (and relatively easy) to check and make sure the object is in the bucket?

2021-11-22 23:29 UTC, helrond approved these changes

2021-11-23 14:05 UTC, p-galligan approved these changes

2021-11-23 21:57 UTC, helrond requested changes
Just add shortuuid to requirements.txt

2021-11-23 21:57 UTC, helrond commented on requirements.txt
> +pytest==6.2.5
Need to add shortuuid

2021-11-23 22:05 UTC, helrond approved these changes

2021-11-24 14:42 UTC, merged